"""J0 of docs/JS8_PLAN.md: shape and internal consistency of the JS8 tables extracted from the
pinned JS8Call source (pluto_tx/js8_tables.py, generated by tools/js8_extract_tables.py), and the
reference data in tests/data/js8/."""
import filecmp
import json
import os
import subprocess
import sys
import tempfile
import unittest
import wave

import numpy as np

from pluto_tx import js8_tables as T

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "tests", "data", "js8")
JS8CALL_SRC = os.environ.get("JS8CALL_SRC", os.path.join(ROOT, "js8call"))


def parity_matrix():
    """87 x 87 bits: row i = which message bits sum (mod 2) to parity bit i (JS8.cpp `parity`,
    4 bits per hex digit, MSB first, the 88th bit of each row unused)."""
    rows = []
    for h in T.PARITY_HEX:
        bits = [int(b) for b in "".join(f"{int(c, 16):04b}" for c in h)][:87]
        rows.append(bits)
    return np.array(rows, dtype=np.uint8)


class ShapeTests(unittest.TestCase):
    def test_source_is_pinned(self):
        self.assertEqual(T.SOURCE["tag"], "v2.5.2")
        self.assertEqual(T.SOURCE["commit"], "f0f0d01b357c8eb8786aee687e8b5c787c787159")

    def test_symbols_and_code_dimensions(self):
        self.assertEqual(T.NUM_SYMBOLS, 79)
        self.assertEqual(T.LDPC["N"], 174)
        self.assertEqual(T.LDPC["K"], 87)
        self.assertEqual(T.LDPC["NS"], 21)
        self.assertEqual(T.LDPC["ND"], 58)
        self.assertEqual(3 * 7 + T.LDPC["ND"], T.NUM_SYMBOLS)       # 3 Costas + 58 data symbols
        self.assertEqual(3 * T.LDPC["ND"], T.LDPC["N"])             # 3 bits per 8-FSK symbol
        self.assertEqual(parity_matrix().shape, (87, 87))
        self.assertEqual(len(T.LDPC_MN), 174)
        self.assertTrue(all(len(m) == 3 for m in T.LDPC_MN))
        self.assertEqual(len(T.LDPC_NM), 87)
        self.assertTrue(all(1 <= len(n) <= 7 for n in T.LDPC_NM))

    def test_costas(self):
        for name in ("ORIGINAL", "MODIFIED"):
            arrays = T.COSTAS[name]
            self.assertEqual(len(arrays), 3)
            for a in arrays:
                self.assertEqual(sorted(a), list(range(7)))       # a permutation of the 8-FSK tones 0..6

    def test_submodes(self):
        want = {0: ("NORMAL", 1920, 15, 500, "ORIGINAL"), 1: ("FAST", 1200, 10, 200, "MODIFIED"),
                2: ("TURBO", 600, 6, 100, "MODIFIED"), 4: ("SLOW", 3840, 30, 500, "MODIFIED")}
        for sm, (name, nsps, period, delay, costas) in want.items():
            d = T.SUBMODES[sm]
            self.assertEqual((d["name"], d["symbol_samples"], d["period_s"], d["start_delay_ms"], d["costas"]),
                             (name, nsps, period, delay, costas))
            self.assertTrue(d["enabled"])
            # the whole transmission fits into the slot
            self.assertLess(d["start_delay_ms"] / 1000 + T.NUM_SYMBOLS * nsps / T.RX_SAMPLE_RATE, period)
        self.assertFalse(T.SUBMODES[8]["enabled"])                  # ULTRA exists but is disabled

    def test_alphabets(self):
        self.assertEqual(len(T.PHY_ALPHABET), 64)
        self.assertEqual(len(set(T.PHY_ALPHABET)), 64)
        self.assertTrue(T.ALPHABET_72.startswith(T.PHY_ALPHABET))   # pack72bits only uses 6-bit indices
        self.assertEqual(len(T.ALPHABET_41), 41)
        self.assertEqual(len(T.ALPHANUMERIC), 39)

    def test_huffman_is_prefix_free(self):
        codes = [c for _, c in T.HUFF_TABLE]
        for a in codes:
            for b in codes:
                if a is not b:
                    self.assertFalse(b.startswith(a), (a, b))

    def test_command_tables(self):
        cmds = dict(T.DIRECTED_CMDS)
        self.assertEqual(cmds[" SNR?"], 0)
        self.assertEqual(cmds[" ACK"], 14)
        self.assertEqual(cmds[" "], 31)
        self.assertTrue(set(T.SNR_CMDS) <= set(T.ALLOWED_CMDS))
        self.assertEqual(T.NBASECALL, 37 * 36 * 10 * 27 * 27 * 27)
        self.assertEqual(dict(T.BASECALLS)["@ALLCALL"], T.NBASECALL + 2)


class LdpcConsistencyTests(unittest.TestCase):
    """The encoder's parity matrix (PARITY_HEX) and the decoder's Tanner graph (LDPC_NM / LDPC_MN) must
    describe the same code, with the codeword order the decoder uses: [87 parity bits | 87 message
    bits] (bpdecode174 copies cw[M:] as the decoded message)."""

    def test_mn_and_nm_are_the_same_graph(self):
        edges_nm = {(bit, chk) for chk, bits in enumerate(T.LDPC_NM) for bit in bits}
        edges_mn = {(bit, chk) for bit, chks in enumerate(T.LDPC_MN) for chk in chks}
        self.assertEqual(edges_nm, edges_mn)

    def test_encoded_codewords_satisfy_all_checks(self):
        p = parity_matrix()
        rng = np.random.default_rng(8)
        for _ in range(20):
            msg = rng.integers(0, 2, 87, dtype=np.uint8)
            cw = np.concatenate([(p @ msg) % 2, msg])
            for chk, bits in enumerate(T.LDPC_NM):
                self.assertEqual(int(cw[list(bits)].sum()) % 2, 0, f"check {chk}")


class ReferenceDataTests(unittest.TestCase):
    def test_vectors_file(self):
        with open(os.path.join(DATA, "vectors.jsonl")) as f:
            cases = [json.loads(line) for line in f]
        self.assertEqual(len(cases), 68)
        for c in cases:
            self.assertIn(c["submode"], (0, 1, 2, 4))
            self.assertTrue(c["frames"])
            for i, fr in enumerate(c["frames"]):
                self.assertEqual(len(fr["frame"]), 12)
                self.assertTrue(set(fr["frame"]) <= set(T.PHY_ALPHABET))
                self.assertEqual(len(fr["tones"]), T.NUM_SYMBOLS)
                tones = [int(x) for x in fr["tones"]]
                costas = T.COSTAS[T.SUBMODES[c["submode"]]["costas"]]
                self.assertEqual((tuple(tones[0:7]), tuple(tones[36:43]), tuple(tones[72:79])), costas)
                self.assertEqual(bool(fr["bits"] & 1), i == 0)                      # JS8CallFirst
                self.assertEqual(bool(fr["bits"] & 2), i == len(c["frames"]) - 1)   # JS8CallLast

    def test_reference_wavs(self):
        d = os.path.join(DATA, "wav")
        with open(os.path.join(d, "decodes.jsonl")) as f:
            decodes = [json.loads(line) for line in f]
        self.assertTrue(decodes)
        total = 0
        for dec in decodes:
            path = os.path.join(d, dec["file"])
            with wave.open(path) as w:
                self.assertEqual((w.getframerate(), w.getnchannels(), w.getsampwidth()), (12000, 1, 2))
                self.assertEqual(w.getnframes(), T.SUBMODES[dec["submode"]]["period_s"] * 12000)
        for root, _, files in os.walk(DATA):
            total += sum(os.path.getsize(os.path.join(root, f)) for f in files)
        self.assertLessEqual(total, 3 * 1024 * 1024)


@unittest.skipUnless(os.path.isdir(os.path.join(JS8CALL_SRC, "JS8_Mode")),
                     "JS8Call source not present (install-js8.sh / JS8CALL_SRC)")
class ExtractorReproducibleTests(unittest.TestCase):
    def test_extractor_reproduces_checked_in_tables(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = os.path.join(tmp, "js8_tables.py")
            subprocess.run([sys.executable, os.path.join(ROOT, "tools", "js8_extract_tables.py"),
                            "--src", JS8CALL_SRC, "--out", out], check=True)
            self.assertTrue(filecmp.cmp(out, os.path.join(ROOT, "pluto_tx", "js8_tables.py"), shallow=False))


if __name__ == "__main__":
    unittest.main()
