#!/usr/bin/env bash
# Starts Web-TRX (GNU Radio backend + built frontend) in the background.
# Manual operation on purpose -- no systemd unit. Stop with scripts/stop.sh,
# status with scripts/status.sh. The TX and RX apps call this same script
# from their "Web-TRX" row (pluto_tx/webtrx_control.py).
#
# Settings: environment variables, or KEY=value lines in web-trx/web-trx.env
# (not committed), e.g.
#   WEB_TRX_PASSWORD=...          login password (generated once and stored here if missing)
#   WEB_TRX_PLUTO_TX_PATH=...     pluto-tx code to use (default: this repo, the parent of web-trx/)
#   WEB_TRX_HOST / WEB_TRX_PORT   listen address (default 0.0.0.0:8321)
#   WEB_TRX_TLS=false             plain http (default: https with a self-signed
#                                 certificate -- browsers only allow microphone
#                                 access over https or on localhost)
#   WEB_TRX_BACKEND=sim           run without hardware
#
# Exit codes: 0 started and confirmed, 3 already running, 4 process is up
# but not confirmed within 60 s (see the log), 1 error.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # web-trx/
REPO_ROOT="$(cd "$ROOT/.." && pwd)"                          # the pluto-tx checkout
RUN_DIR="$ROOT/run"
PID_FILE="$RUN_DIR/web-trx.pid"
LOG_FILE="$RUN_DIR/web-trx.log"

mkdir -p "$RUN_DIR"

# One start/stop at a time (the apps' buttons, the launcher and a terminal
# can all call this). A second start waits and then finds the server running.
exec 9>"$RUN_DIR/start.lock"
if ! flock -w 70 9; then
  echo "Ein anderer Start/Stopp von Web-TRX läuft noch (Sperre $RUN_DIR/start.lock)." >&2
  exit 1
fi

# A PID file counts only while that process is alive AND is our uvicorn --
# after a reboot the PID may belong to any unrelated process.
is_webtrx_pid() {
  [[ "$1" =~ ^[0-9]+$ ]] && kill -0 "$1" 2>/dev/null \
    && grep -qa uvicorn "/proc/$1/cmdline" 2>/dev/null \
    && grep -qa web_trx.server "/proc/$1/cmdline" 2>/dev/null
}

if [[ -f "$PID_FILE" ]]; then
  OLD_PID="$(cat "$PID_FILE" 2>/dev/null || true)"
  if is_webtrx_pid "$OLD_PID"; then
    echo "Web-TRX läuft bereits (PID $OLD_PID). Stoppen mit web-trx/scripts/stop.sh"
    exit 3
  fi
  rm -f "$PID_FILE"   # stale
fi

if [[ -f "$ROOT/web-trx.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  . "$ROOT/web-trx.env"
  set +a
fi

# A stable password: generated once and kept in web-trx.env, so restarts
# (together with the persisted sessions below) don't force a new login.
if [[ -z "${WEB_TRX_PASSWORD:-}" ]]; then
  WEB_TRX_PASSWORD="$(python3 -c 'import secrets; print(secrets.token_urlsafe(12))')"
  touch "$ROOT/web-trx.env" && chmod 600 "$ROOT/web-trx.env"
  printf '\n# generated by scripts/start.sh\nWEB_TRX_PASSWORD=%s\n' "$WEB_TRX_PASSWORD" >>"$ROOT/web-trx.env"
  echo "Neues Login-Passwort erzeugt und in web-trx/web-trx.env gespeichert: $WEB_TRX_PASSWORD"
fi
export WEB_TRX_PASSWORD

export WEB_TRX_BACKEND="${WEB_TRX_BACKEND:-gnuradio}"
export WEB_TRX_PLUTO_TX_PATH="${WEB_TRX_PLUTO_TX_PATH:-$REPO_ROOT}"
export WEB_TRX_STATIC_DIR="$ROOT/frontend/dist"
export WEB_TRX_TX_LOG_PATH="${WEB_TRX_TX_LOG_PATH:-$RUN_DIR/web_trx_tx_log.sqlite3}"
export WEB_TRX_SETTINGS_PATH="${WEB_TRX_SETTINGS_PATH:-$RUN_DIR/settings.json}"
export WEB_TRX_SESSIONS_PATH="${WEB_TRX_SESSIONS_PATH:-$RUN_DIR/sessions.json}"
HOST="${WEB_TRX_HOST:-0.0.0.0}"
PORT="${WEB_TRX_PORT:-8321}"

# Same library/module paths as pluto-tx's own launcher: gr-m17 lives under
# ~/.local (shared library + Python module in the user site-packages, which a
# venv does not see by default) and RADE next to the pluto-tx checkout.
export LD_LIBRARY_PATH="$WEB_TRX_PLUTO_TX_PATH/rade_c/build/src:$HOME/.local/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH:-}"
export PATH="$WEB_TRX_PLUTO_TX_PATH/rade_c/build/src:$PATH"
PYTHONPATH="$(python3 -m site --user-site):${PYTHONPATH:-}"
export PYTHONPATH

VENV="$ROOT/backend/.venv"
if [[ ! -x "$VENV/bin/uvicorn" ]]; then
  echo "Backend-venv fehlt -- einmal ./install-web-trx.sh im pluto-tx-Verzeichnis ausführen." >&2
  exit 1
fi

if [[ ! -f "$ROOT/frontend/dist/index.html" || "${1:-}" == "--build" ]]; then
  echo "Baue Frontend ..."
  (cd "$ROOT/frontend" && { [[ -d node_modules ]] || npm ci --silent; } && npm run build --silent)
fi

SCHEME=http
TLS_ARGS=()
if [[ "${WEB_TRX_TLS:-true}" == "true" ]]; then
  TLS_DIR="$RUN_DIR/tls"
  if [[ ! -f "$TLS_DIR/cert.pem" ]]; then
    mkdir -p "$TLS_DIR"
    SAN="DNS:localhost,DNS:$(hostname),IP:127.0.0.1"
    for ip in $(hostname -I); do case "$ip" in *:*) ;; *) SAN="$SAN,IP:$ip" ;; esac; done
    (umask 077 && openssl req -x509 -newkey rsa:2048 -nodes -days 3650 -subj "/CN=web-trx" \
      -addext "subjectAltName=$SAN" -keyout "$TLS_DIR/key.pem" -out "$TLS_DIR/cert.pem" 2>/dev/null)
    echo "Selbstsigniertes Zertifikat erzeugt: $TLS_DIR/cert.pem"
  fi
  TLS_ARGS=(--ssl-keyfile "$TLS_DIR/key.pem" --ssl-certfile "$TLS_DIR/cert.pem")
  export WEB_TRX_COOKIE_SECURE=true
  SCHEME=https
fi

cd "$ROOT/backend"
# The RADE decoder inside the RX flowgraph prints a sync-state line many
# times a second (from C, not suppressible from Python) -- kept out of the
# log. Process substitution keeps $! pointing at uvicorn itself.
: >"$LOG_FILE"
# WebSocket pings every 10 s (10 s timeout): a browser that vanished without
# closing (network gone) counts as gone after at most ~20 s, which starts the
# "no operator" watchdog (backend web_trx/session.py).
# 9>&- on both the server and the log filter: neither may inherit the start
# lock, or it would stay locked for the server's whole lifetime.
nohup "$VENV/bin/uvicorn" web_trx.server:create_app --factory --host "$HOST" --port "$PORT" "${TLS_ARGS[@]}" \
  --ws-ping-interval 10 --ws-ping-timeout 10 \
  > >(grep --line-buffered -v -E '^[0-9]+ state: ' >>"$LOG_FILE" 2>/dev/null 9>&-) 2>&1 </dev/null 9>&- &
PID=$!
echo "$PID" >"$PID_FILE"

CONFIRMED=0
for _ in $(seq 1 120); do
  if grep -q "Application startup complete" "$LOG_FILE" 2>/dev/null; then
    CONFIRMED=1
    break
  fi
  if ! kill -0 "$PID" 2>/dev/null; then
    echo "Start fehlgeschlagen, Log: $LOG_FILE" >&2
    tail -n 20 "$LOG_FILE" >&2 || true
    rm -f "$PID_FILE"
    exit 1
  fi
  sleep 0.5
done

if [[ "$CONFIRMED" != 1 ]]; then
  echo "Web-TRX-Prozess läuft (PID $PID), aber noch keine Startbestätigung nach 60 s. Log: $LOG_FILE"
  exit 4
fi

echo "Web-TRX läuft (PID $PID, Backend: $WEB_TRX_BACKEND)"
for ip in $(hostname -I 2>/dev/null || true); do
  case "$ip" in 169.254.*|*:*) ;; *) echo "  $SCHEME://$ip:$PORT" ;; esac
done
echo "  Log: $LOG_FILE"
